---
apiVersion: v1
kind: Service
metadata:
  name: rti-cloud-discovery-service
  release: {{ .Release.Name }}
spec:
  ports:
  - port: 7400
    protocol: UDP
    targetPort: 7400
  selector:
    app: rti-cloud-discovery-service
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
