---
apiVersion: v1
kind: Pod
metadata:
  name: rti-cloud-discovery-service
  labels:
    app: rti-cloud-discovery-service
spec:
  containers:
    - name: rti-cloud-discovery-service
      image: {{ .Values.registry.url }}/{{ .Values.cloudDiscoveryService.image.name }}:{{ .Values.cloudDiscoveryService.image.tag }}
      resources:
        requests:
          cpu: {{ quote .Values.cloudDiscoveryService.resources.requests.cpu }}
          memory: {{ quote .Values.cloudDiscoveryService.resources.requests.memory }}
        limits:
          cpu: {{ quote .Values.cloudDiscoveryService.resources.limits.cpu }}
          memory: {{ quote .Values.cloudDiscoveryService.resources.limits.memory }}
      args:
        - "-cfgName"
        - "{{ .Values.cloudDiscoveryService.cfgName }}"
        - "-verbosity"
        - "{{ .Values.cloudDiscoveryService.verbosity }}"
      volumeMounts:
      - name: rti-cloud-discovery-service
        mountPath: /app
      ports:
        - containerPort: 7400
          protocol: "UDP"
          name: "rtps2-disc-mult"
  imagePullSecrets:
    - name: {{ .Values.registry.pullSecret }}
  volumes:
    - name: rti-cloud-discovery-service
      configMap:
        name: rti-cloud-discovery-service
  restartPolicy: Always
