apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dds-examples
data:
  USER_QOS_PROFILES.xml: |
{{ .Files.Get "files/dds-examples/USER_QOS_PROFILES.xml" | printf "%s" | indent 4 }}
